name: hybrid_rc_ngrc_environment
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - joblib
  - tqdm
  - numba
  - pip=23.3=py311hca03da5_0
  - pip:
      - dysts==0.1
